### ISSUE TITLE
NullPointerException when using reader.setId() inside python script

### ISSUE THREAD

**Issue by sebi06** [openmicroscopy/bioformats#3367] opened 2019-05-10 05:57 UTC
HI guys,

I recently encountered the issue that reading metadata from a file using BioFormtas in Fiji works locally fine, no matter if I use *.ome.tiff or *.ome.tif (at least for my windows 10 system)

This is surprisingly not the case when I was running the same code inside an Ubuntu based docker container, where *.ome.tiff works *.ome.tif cause the exception.

For more details see the post:

[NullPointerException when using reader.setId() inside python script](https://forum.image.sc/t/nullpointerexception-when-using-reader-setid-inside-python-script/25508?u=sebi06)

Maybe some can give me a hint on how to avoid this issue?

**Comment by sbesson** [comment] 2019-05-10 07:23
Thanks @sebi06 for the report. Closing as a duplicate of #3343.  Moving the data into a subfolder should be a workaround with Bio-Formats 6.0.x. A proper fix will be included in Bio-Formats 6.1.0.

**Closed by sbesson** 2019-05-10 07:23 UTC
