### ISSUE TITLE
Problem loading Picoquant .bin files

### ISSUE THREAD

**Issue by seanwarren** [openmicroscopy/bioformats#2079] opened 2015-11-11 08:46 UTC
I'm having some problems loading a Picoquant .bin file using bioformats. The file is here:
https://www.dropbox.com/s/k03jdxgpxhxs9ui/VLDLR_mGFP_with%20ligand%20%20.zip?dl=0

The file is 128x128 pixels with 3125 channels.
I've that it conforms correctly to the format specified by Picoquant: http://www.tcspc.com/doku.php/glossary:pre-histogrammed_image and I'm able to read it correctly in Matlab.

Bioformats however returns a width of 0px and a height of 204,816,160px.

The first 16 bytes of the data are: `80 00 00 00 | 80 00 00 00 | 00 00 20 3f | 35 0c 00 00` which correspond to the width (int32), height(int32), px res (float) and number of channels (int32) respectively. 

The returned height, 204,816,160, is `20 3f 35 0c` in hex. It looks to me like somehow the first 6 bytes might be getting discarded? Looking at PQBinReader.java it's not obvious to me how that might be happening though.

Any ideas would be greatly appreciated! 
@imunro have you seen anything like this before?

Cheers
Sean

**Comment by imunro** [comment] 2015-11-11 09:25
Looking now. If I can fix quickly I might be able to get the fix into the next bf release.

**Comment by imunro** [comment] 2015-11-11 11:50
Hi @seanwarren 

I just imported this to an OMERO server and , although it took forever it looks like the attached. Hope you can see that .
If those dimensions look right then that would suggest it isn’t bio-formats.
Can I ask which version you have?

The slowness is a separate issue related to file size. I know what it is (I can  bore you with details if you want).
If you’re going to be using .bin files of this sort of size with any regularity then we need to address this.
Please let me know.

Ian


<img width="524" alt="screen shot 2015-11-11 at 11 38 26" src="https://cloud.githubusercontent.com/assets/1183110/11090483/38447d0e-886a-11e5-9996-ec805cf864c2.png">

**Comment by imunro** [comment] 2015-11-11 12:22
Just also checked with Ff from source & again I'm getting 128x128x3125.

**Comment by melissalinkert** [comment] 2015-11-24 15:51
@seanwarren, @imunro: is this still an issue with 5.1.6?

**Comment by imunro** [comment] 2015-11-24 16:51
@melissalinkert as in the comments, I failed to reproduce the reported problem with dimensions with bf 5.1.4. & han;t yet tried with 5.1.6 The slowness is a separate issue. If the whole file is below some threshold size (currently 200x200x900), the reader buffers the data in memory and then returns each plane from this buffer. Beyond this size, each plane is read into memory individually (requiring the whole file to be read for each plane) .  Speed-up would require a cleverer buffering system to buffer parts of the file.

**Comment by sbesson** [comment] 2016-04-19 14:14
@imunro: what's the status of this issue with the improvements of https://github.com/openmicroscopy/bioformats/pull/2332?

**Comment by imunro** [comment] 2016-04-19 14:38
It looks, from the comments that bf always got the correct dimensions for this file. 
If the issue was slow loading that should now have been addressed. Would be good to check though but I can't see a QA No for this file.

**Comment by sbesson** [comment] 2016-04-19 14:44
The file mentioned in the PR description has certainly been added to the curated data repository, loading has been tested as part of https://github.com/openmicroscopy/bioformats/pull/2332#issuecomment-208334155 and it is now included as part of the daily Bio-Formats automated tests. Closing this issue. @seanwarren: would it be okay to make this sample file public?

**Closed by sbesson** 2016-04-19 14:44 UTC

**Comment by seanwarren** [comment] 2016-04-20 01:35
@sbesson that's fine, but would you mind changing the file name to something more generic please as this is a collaborators data.
